/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as NodesIdRouteImport } from './routes/nodes.$id'
import { Route as DeploymentsIdRouteImport } from './routes/deployments.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NodesRoute,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeploymentsRoute,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NodesRoute,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeploymentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/models': typeof ModelsRoute
  '/nodes': typeof NodesRouteWithChildren
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/nodes/$id': typeof NodesIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/nodes/': typeof NodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/nodes/$id': typeof NodesIdRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/nodes': typeof NodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/models': typeof ModelsRoute
  '/nodes': typeof NodesRouteWithChildren
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/nodes/$id': typeof NodesIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/nodes/': typeof NodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deployments'
    | '/models'
    | '/nodes'
    | '/operations'
    | '/settings'
    | '/setup'
    | '/deployments/$id'
    | '/nodes/$id'
    | '/deployments/'
    | '/nodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/operations'
    | '/settings'
    | '/setup'
    | '/deployments/$id'
    | '/nodes/$id'
    | '/deployments'
    | '/nodes'
  id:
    | '__root__'
    | '/'
    | '/deployments'
    | '/models'
    | '/nodes'
    | '/operations'
    | '/settings'
    | '/setup'
    | '/deployments/$id'
    | '/nodes/$id'
    | '/deployments/'
    | '/nodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeploymentsRoute: typeof DeploymentsRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  NodesRoute: typeof NodesRouteWithChildren
  OperationsRoute: typeof OperationsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof NodesRoute
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof DeploymentsRoute
    }
    '/nodes/$id': {
      id: '/nodes/$id'
      path: '/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof NodesRoute
    }
    '/deployments/$id': {
      id: '/deployments/$id'
      path: '/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof DeploymentsRoute
    }
  }
}

interface DeploymentsRouteChildren {
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
}

const DeploymentsRouteChildren: DeploymentsRouteChildren = {
  DeploymentsIdRoute: DeploymentsIdRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
}

const DeploymentsRouteWithChildren = DeploymentsRoute._addFileChildren(
  DeploymentsRouteChildren,
)

interface NodesRouteChildren {
  NodesIdRoute: typeof NodesIdRoute
  NodesIndexRoute: typeof NodesIndexRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesIdRoute: NodesIdRoute,
  NodesIndexRoute: NodesIndexRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeploymentsRoute: DeploymentsRouteWithChildren,
  ModelsRoute: ModelsRoute,
  NodesRoute: NodesRouteWithChildren,
  OperationsRoute: OperationsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
